#pragma once

#ifndef CONFIG_ECHOMATE_CAMERA_FPS
#define CONFIG_ECHOMATE_CAMERA_FPS 30
#endif

#ifndef CONFIG_ECHOMATE_CAMERA_TARGET_WIDTH
#define CONFIG_ECHOMATE_CAMERA_TARGET_WIDTH 640
#endif

#ifndef CONFIG_ECHOMATE_CAMERA_TARGET_HEIGHT
#define CONFIG_ECHOMATE_CAMERA_TARGET_HEIGHT 480
#endif

#ifndef CONFIG_ECHOMATE_CAMERA_PREVIEW_FPS
#define CONFIG_ECHOMATE_CAMERA_PREVIEW_FPS 30
#endif

#ifndef CONFIG_ECHOMATE_VISION_INPUT_WIDTH
#define CONFIG_ECHOMATE_VISION_INPUT_WIDTH 96
#endif

#ifndef CONFIG_ECHOMATE_VISION_INPUT_HEIGHT
#define CONFIG_ECHOMATE_VISION_INPUT_HEIGHT 96
#endif

#if !defined(CONFIG_ECHOMATE_VISION_MODEL_INPUT_GRAY8) && \
    !defined(CONFIG_ECHOMATE_VISION_MODEL_INPUT_RGB888)
#define CONFIG_ECHOMATE_VISION_MODEL_INPUT_GRAY8 1
#endif

#ifndef CONFIG_ECHOMATE_VISION_WARN_INFERENCE_MS
#define CONFIG_ECHOMATE_VISION_WARN_INFERENCE_MS 100
#endif

#ifndef CONFIG_ECHOMATE_VISION_WARN_STALE_FRAMES
#define CONFIG_ECHOMATE_VISION_WARN_STALE_FRAMES 0
#endif

#ifndef CONFIG_ECHOMATE_VISION_FACE_CONFIRM_FRAMES
#define CONFIG_ECHOMATE_VISION_FACE_CONFIRM_FRAMES 2
#endif

#ifndef CONFIG_ECHOMATE_VISION_FACE_HOLD_FRAMES
#define CONFIG_ECHOMATE_VISION_FACE_HOLD_FRAMES 10
#endif

#ifndef CONFIG_ECHOMATE_VISION_FACE_SMOOTH_Q8
#define CONFIG_ECHOMATE_VISION_FACE_SMOOTH_Q8 96
#endif

#ifndef CONFIG_ECHOMATE_CAMERA_RAW_BLACK_LEVEL
#define CONFIG_ECHOMATE_CAMERA_RAW_BLACK_LEVEL 16
#endif

#if !defined(CONFIG_ECHOMATE_FACE_DETECTOR_HEURISTIC) && \
    !defined(CONFIG_ECHOMATE_FACE_DETECTOR_ESP_WHO) && \
    !defined(CONFIG_ECHOMATE_FACE_DETECTOR_ESP_DL)
#define CONFIG_ECHOMATE_FACE_DETECTOR_HEURISTIC 1
#endif

#ifndef CONFIG_ECHOMATE_FACE_HEURISTIC_MIN_LUMA
#define CONFIG_ECHOMATE_FACE_HEURISTIC_MIN_LUMA 22
#endif

#ifndef CONFIG_ECHOMATE_FACE_HEURISTIC_MIN_CONTRAST
#define CONFIG_ECHOMATE_FACE_HEURISTIC_MIN_CONTRAST 12
#endif

#ifndef CONFIG_ECHOMATE_FACE_HEURISTIC_MIN_CENTER_CONTRAST
#define CONFIG_ECHOMATE_FACE_HEURISTIC_MIN_CENTER_CONTRAST 14
#endif

#if !defined(CONFIG_ECHOMATE_CAMERA_BAYER_BGGR) && \
    !defined(CONFIG_ECHOMATE_CAMERA_BAYER_GBRG) && \
    !defined(CONFIG_ECHOMATE_CAMERA_BAYER_GRBG) && \
    !defined(CONFIG_ECHOMATE_CAMERA_BAYER_RGGB)
#define CONFIG_ECHOMATE_CAMERA_BAYER_BGGR 1
#endif

#ifndef CONFIG_ECHOMATE_AUDIO_SAMPLE_RATE
#define CONFIG_ECHOMATE_AUDIO_SAMPLE_RATE 16000
#endif

#ifndef CONFIG_ECHOMATE_LOUD_AMPLITUDE
#define CONFIG_ECHOMATE_LOUD_AMPLITUDE 22000
#endif

#ifndef CONFIG_ECHOMATE_LONELY_TIMEOUT_MS
#define CONFIG_ECHOMATE_LONELY_TIMEOUT_MS 10000
#endif

#ifndef CONFIG_ECHOMATE_SLEEPY_TIMEOUT_MS
#define CONFIG_ECHOMATE_SLEEPY_TIMEOUT_MS 20000
#endif

#ifndef CONFIG_ECHOMATE_ENABLE_CAMERA_DRIVER
#define CONFIG_ECHOMATE_ENABLE_CAMERA_DRIVER 0
#endif

#ifndef CONFIG_ECHOMATE_ENABLE_AUDIO_DRIVER
#define CONFIG_ECHOMATE_ENABLE_AUDIO_DRIVER 0
#endif

#ifndef CONFIG_ECHOMATE_ENABLE_SERVO
#define CONFIG_ECHOMATE_ENABLE_SERVO 0
#endif

#ifndef CONFIG_ECHOMATE_ENABLE_WIFI
#define CONFIG_ECHOMATE_ENABLE_WIFI 0
#endif

#ifndef CONFIG_ECHOMATE_ENABLE_LVGL
#define CONFIG_ECHOMATE_ENABLE_LVGL 0
#endif

#ifndef CONFIG_ECHOMATE_ENABLE_LCD_MIPI_DSI
#define CONFIG_ECHOMATE_ENABLE_LCD_MIPI_DSI 0
#endif

#ifndef CONFIG_ECHOMATE_LCD_TEST_PATTERN
#define CONFIG_ECHOMATE_LCD_TEST_PATTERN 1
#endif

#ifndef CONFIG_ECHOMATE_LCD_DPI_CLK_MHZ
#define CONFIG_ECHOMATE_LCD_DPI_CLK_MHZ 48
#endif

#ifndef CONFIG_ECHOMATE_LCD_H_RES
#define CONFIG_ECHOMATE_LCD_H_RES 1024
#endif

#ifndef CONFIG_ECHOMATE_LCD_V_RES
#define CONFIG_ECHOMATE_LCD_V_RES 600
#endif

#ifndef CONFIG_ECHOMATE_LCD_LDO_CHAN
#define CONFIG_ECHOMATE_LCD_LDO_CHAN 3
#endif

#ifndef CONFIG_ECHOMATE_LCD_LDO_MV
#define CONFIG_ECHOMATE_LCD_LDO_MV 2500
#endif

#ifndef CONFIG_ECHOMATE_ENABLE_ESP_WHO
#define CONFIG_ECHOMATE_ENABLE_ESP_WHO 0
#endif

#ifndef CONFIG_ECHOMATE_ESP_WHO_WAIT_UI_READY
#define CONFIG_ECHOMATE_ESP_WHO_WAIT_UI_READY 1
#endif

#ifndef CONFIG_ECHOMATE_ESP_WHO_INIT_DELAY_MS
#define CONFIG_ECHOMATE_ESP_WHO_INIT_DELAY_MS 1500
#endif

#ifndef CONFIG_ECHOMATE_ESP_WHO_INFERENCE_INTERVAL
#define CONFIG_ECHOMATE_ESP_WHO_INFERENCE_INTERVAL 6
#endif

#ifndef CONFIG_ECHOMATE_ESP_WHO_MIN_CONFIDENCE
#define CONFIG_ECHOMATE_ESP_WHO_MIN_CONFIDENCE 62
#endif

#ifndef CONFIG_ECHOMATE_ESP_WHO_MIN_BOX_PERCENT
#define CONFIG_ECHOMATE_ESP_WHO_MIN_BOX_PERCENT 3
#endif

#ifndef CONFIG_ECHOMATE_ESP_WHO_MAX_BOX_PERCENT
#define CONFIG_ECHOMATE_ESP_WHO_MAX_BOX_PERCENT 82
#endif

#ifndef CONFIG_ECHOMATE_ESP_WHO_MIN_ASPECT_Q8
#define CONFIG_ECHOMATE_ESP_WHO_MIN_ASPECT_Q8 140
#endif

#ifndef CONFIG_ECHOMATE_ESP_WHO_MAX_ASPECT_Q8
#define CONFIG_ECHOMATE_ESP_WHO_MAX_ASPECT_Q8 390
#endif

#ifndef CONFIG_ECHOMATE_ESP_WHO_ENABLE_ROI_CHECK
#define CONFIG_ECHOMATE_ESP_WHO_ENABLE_ROI_CHECK 1
#endif

#ifndef CONFIG_ECHOMATE_ESP_WHO_ROI_MIN_LUMA
#define CONFIG_ECHOMATE_ESP_WHO_ROI_MIN_LUMA 12
#endif

#ifndef CONFIG_ECHOMATE_ESP_WHO_ROI_MAX_LUMA
#define CONFIG_ECHOMATE_ESP_WHO_ROI_MAX_LUMA 250
#endif

#ifndef CONFIG_ECHOMATE_ESP_WHO_ROI_MIN_CONTRAST
#define CONFIG_ECHOMATE_ESP_WHO_ROI_MIN_CONTRAST 6
#endif

#ifndef CONFIG_ECHOMATE_ESP_WHO_ROI_MAX_CHANNEL_SPREAD
#define CONFIG_ECHOMATE_ESP_WHO_ROI_MAX_CHANNEL_SPREAD 180
#endif

#ifndef CONFIG_ECHOMATE_ENABLE_EXPRESSION_HEURISTIC
#define CONFIG_ECHOMATE_ENABLE_EXPRESSION_HEURISTIC 1
#endif

#if !defined(CONFIG_ECHOMATE_EXPRESSION_BACKEND_HEURISTIC) && \
    !defined(CONFIG_ECHOMATE_EXPRESSION_BACKEND_ESP_DL) && \
    !defined(CONFIG_ECHOMATE_EXPRESSION_BACKEND_STUB)
#define CONFIG_ECHOMATE_EXPRESSION_BACKEND_HEURISTIC 1
#endif

#ifndef CONFIG_ECHOMATE_EXPRESSION_HAPPY_MIN_CONFIDENCE
#define CONFIG_ECHOMATE_EXPRESSION_HAPPY_MIN_CONFIDENCE 95
#endif

#ifndef CONFIG_ECHOMATE_EXPRESSION_HAPPY_MIN_CONTRAST
#define CONFIG_ECHOMATE_EXPRESSION_HAPPY_MIN_CONTRAST 42
#endif

#ifndef CONFIG_ECHOMATE_EXPRESSION_HAPPY_LOWER_DARK_DELTA
#define CONFIG_ECHOMATE_EXPRESSION_HAPPY_LOWER_DARK_DELTA 4
#endif

#ifndef CONFIG_ECHOMATE_EXPRESSION_HAPPY_MIN_LOWER_CONTRAST
#define CONFIG_ECHOMATE_EXPRESSION_HAPPY_MIN_LOWER_CONTRAST 42
#endif

#ifndef CONFIG_ECHOMATE_EXPRESSION_HAPPY_MIN_MOUTH_CONTRAST
#define CONFIG_ECHOMATE_EXPRESSION_HAPPY_MIN_MOUTH_CONTRAST 60
#endif

#ifndef CONFIG_ECHOMATE_EXPRESSION_HAPPY_MOUTH_PROMINENCE
#define CONFIG_ECHOMATE_EXPRESSION_HAPPY_MOUTH_PROMINENCE 18
#endif

#ifndef CONFIG_ECHOMATE_EXPRESSION_HAPPY_MOUTH_OVER_LOWER
#define CONFIG_ECHOMATE_EXPRESSION_HAPPY_MOUTH_OVER_LOWER 12
#endif

#ifndef CONFIG_ECHOMATE_EXPRESSION_HAPPY_BROAD_MIN_UPPER_CONTRAST
#define CONFIG_ECHOMATE_EXPRESSION_HAPPY_BROAD_MIN_UPPER_CONTRAST 220
#endif

#ifndef CONFIG_ECHOMATE_EXPRESSION_HAPPY_BROAD_MIN_LOWER_CONTRAST
#define CONFIG_ECHOMATE_EXPRESSION_HAPPY_BROAD_MIN_LOWER_CONTRAST 230
#endif

#ifndef CONFIG_ECHOMATE_EXPRESSION_HAPPY_BROAD_MIN_MOUTH_CONTRAST
#define CONFIG_ECHOMATE_EXPRESSION_HAPPY_BROAD_MIN_MOUTH_CONTRAST 160
#endif

#ifndef CONFIG_ECHOMATE_EXPRESSION_SAD_MAX_LUMA
#define CONFIG_ECHOMATE_EXPRESSION_SAD_MAX_LUMA 48
#endif

#ifndef CONFIG_ECHOMATE_EXPRESSION_SAD_MAX_CONTRAST
#define CONFIG_ECHOMATE_EXPRESSION_SAD_MAX_CONTRAST 18
#endif

#ifndef CONFIG_ECHOMATE_EXPRESSION_NON_NEUTRAL_CONFIRM_FRAMES
#define CONFIG_ECHOMATE_EXPRESSION_NON_NEUTRAL_CONFIRM_FRAMES 4
#endif

#ifndef CONFIG_ECHOMATE_EXPRESSION_NEUTRAL_CONFIRM_FRAMES
#define CONFIG_ECHOMATE_EXPRESSION_NEUTRAL_CONFIRM_FRAMES 3
#endif

#ifndef CONFIG_ECHOMATE_EXPRESSION_HOLD_FRAMES
#define CONFIG_ECHOMATE_EXPRESSION_HOLD_FRAMES 0
#endif

#ifndef CONFIG_ECHOMATE_EXPRESSION_ESP_DL_INPUT_WIDTH
#define CONFIG_ECHOMATE_EXPRESSION_ESP_DL_INPUT_WIDTH 96
#endif

#ifndef CONFIG_ECHOMATE_EXPRESSION_ESP_DL_INPUT_HEIGHT
#define CONFIG_ECHOMATE_EXPRESSION_ESP_DL_INPUT_HEIGHT 96
#endif

#ifndef CONFIG_ECHOMATE_EXPRESSION_ESP_DL_INPUT_RGB888
#define CONFIG_ECHOMATE_EXPRESSION_ESP_DL_INPUT_RGB888 1
#endif

#ifndef CONFIG_ECHOMATE_EXPRESSION_ESP_DL_MIN_CONFIDENCE
#define CONFIG_ECHOMATE_EXPRESSION_ESP_DL_MIN_CONFIDENCE 55
#endif

#ifndef CONFIG_ECHOMATE_EXPRESSION_SAMPLE_LOG_ENABLE
#define CONFIG_ECHOMATE_EXPRESSION_SAMPLE_LOG_ENABLE 0
#endif

#ifndef CONFIG_ECHOMATE_EXPRESSION_SAMPLE_LOG_PERIOD_MS
#define CONFIG_ECHOMATE_EXPRESSION_SAMPLE_LOG_PERIOD_MS 1000
#endif

#ifndef CONFIG_ECHOMATE_EXPRESSION_SAMPLE_GRID_SIZE
#define CONFIG_ECHOMATE_EXPRESSION_SAMPLE_GRID_SIZE 8
#endif

#ifndef CONFIG_ECHOMATE_ENABLE_ESP_DL
#define CONFIG_ECHOMATE_ENABLE_ESP_DL 0
#endif

#ifndef CONFIG_ECHOMATE_SERVO0_GPIO
#define CONFIG_ECHOMATE_SERVO0_GPIO -1
#endif

#ifndef CONFIG_ECHOMATE_SERVO1_GPIO
#define CONFIG_ECHOMATE_SERVO1_GPIO -1
#endif

#ifndef CONFIG_ECHOMATE_SERVO_MIN_US
#define CONFIG_ECHOMATE_SERVO_MIN_US 500
#endif

#ifndef CONFIG_ECHOMATE_SERVO_MAX_US
#define CONFIG_ECHOMATE_SERVO_MAX_US 2500
#endif

#define ECHOMATE_STACK_CAMERA   6144
#define ECHOMATE_STACK_VISION   6144
#define ECHOMATE_STACK_AUDIO    6144
#define ECHOMATE_STACK_EMOTION  4096
#define ECHOMATE_STACK_DIALOGUE 4096
#define ECHOMATE_STACK_UI       4096
#define ECHOMATE_STACK_MOTION   4096
#define ECHOMATE_STACK_NETWORK  4096

#define ECHOMATE_PRIO_AUDIO     10
#define ECHOMATE_PRIO_VISION    4
#define ECHOMATE_PRIO_CAMERA    8
#define ECHOMATE_PRIO_EMOTION   7
#define ECHOMATE_PRIO_MOTION    6
#define ECHOMATE_PRIO_DIALOGUE  5
#define ECHOMATE_PRIO_UI        8
#define ECHOMATE_PRIO_NETWORK   4
